compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmAlwaysAuth: false

npmAuditRegistry: 'https://registry.yarnpkg.com'

npmRegistryServer: 'https://registry.yarnpkg.com'

plugins:
  - path: .proactive/yarn-plugins/plugin-cache-dir.cjs
    spec: '@proactive/plugin-cache-dir'

yarnPath: .yarn/releases/yarn-4.0.0-rc.53.cjs
