nodeLinker: node-modules

npmAlwaysAuth: true

npmAuditRegistry: 'https://registry.yarnpkg.com'

npmRegistryServer: 'https://pkgs.dev.azure.com/swisslife/_packaging/NpmMain/npm/registry'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@/plugin-cache-dir.cjs
    spec: '@/plugin-cache-dir'

yarnPath: .yarn/releases/yarn-3.2.0.cjs
