nodeLinker: node-modules

npmAlwaysAuth: false

npmAuditRegistry: 'https://registry.yarnpkg.com'

npmRegistryServer: 'https://registry.yarnpkg.com'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .proactive/yarn-plugins/plugin-cache-dir.cjs
    spec: '@proactive/plugin-cache-dir'

yarnPath: .yarn/releases/yarn-3.2.2.cjs
