compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmAlwaysAuth: false

npmAuditRegistry: 'https://registry.yarnpkg.com'

npmRegistryServer: 'https://registry.yarnpkg.com'

yarnPath: .yarn/releases/yarn-4.0.0-rc.53.cjs
